############################
########## <Post> ##########
############################

### Create Post
POST http://localhost:3000/post
Content-Type: application/json

{
  "title": "First Post",
  "body": "This is my first post",
  "senderID": "64bfa12c9e1a4a00123abcd1"
}

### Get All Posts
GET http://localhost:3000/post

### Get Post By ID
GET http://localhost:3000/post/6974bc1db5a9c8273fdb1001

### Get Posts By Sender
GET http://localhost:3000/post?senderID=64bfa12c9e1a4a00123abcd1

### Update Post
PUT http://localhost:3000/post/6974bc1db5a9c8273fdb1001
Content-Type: application/json

{
  "title": "Updated Post Title",
  "body": "Updated content"
}

### Delete Post
DELETE http://localhost:3000/post/6974bc1db5a9c8273fdb1001
