############################
########## <Post> ##########
############################

### Create Post
POST http://localhost:3000/post
Content-Type: application/json

{
  "title": "First Post",
  "body": "This is my first post",
  "senderID": "64bfa12c9e1a4a00123abcd1"
}

### Get All Posts
GET http://localhost:3000/post

### Get Post By ID
GET http://localhost:3000/post/6974bc1db5a9c8273fdb1001

### Get Posts By Sender
GET http://localhost:3000/post?senderID=64bfa12c9e1a4a00123abcd1

### Update Post
PUT http://localhost:3000/post/6974bc1db5a9c8273fdb1001
Content-Type: application/json

{
  "title": "Updated Post Title",
  "body": "Updated content"
}

### Delete Post
DELETE http://localhost:3000/post/6974bc1db5a9c8273fdb1001



###############################
########## <Comment> ##########
###############################

### Create Comment
POST http://localhost:3000/comment
Content-Type: application/json

{
  "postID": "6974d8dcd4ef218ff6327e09",
  "userID": "64bfa12c9e1a4a00123abcd1",
  "content": "Nice Post!!!"
}

### Get All Comments
GET http://localhost:3000/comment

### Get Comment By ID
GET http://localhost:3000/comment/6974dbc35c0d03185d66c8bf

### Get Comments By Post
GET http://localhost:3000/comment?postID=6974d8dcd4ef218ff6327e09

### Update Comment
PUT http://localhost:3000/comment/6974dbc35c0d03185d66c8bf
Content-Type: application/json

{
  "content": "Edited comment content"
}

### Delete Comment
DELETE http://localhost:3000/comment/6974dbc35c0d03185d66c8bf